# ======================================================
# Detector geometry setup  (/det/)
# ======================================================

# Pinpoint Geometry
/det/setNumPinpointLayers 6
/det/setTungstenThickness 5 mm

/det/setPixelDetectorOffsetX 0.0 mm
/det/setPixelDetectorOffsetY 0.0 mm
/det/setSiliconThickness 10 um

# Pixel dimensions
/det/setPixelHeight 22.8 um
/det/setPixelWidth 20.8 um

# Overall detector transverse size
/det/setDetectorWidth 25 cm
/det/setDetectorHeight 20 cm

# Fortune Geometry
/det/setNumFortuneBlocks 7
/det/setNumScintLayers 8

# Scintillator configuration
/det/setScintDetectorOffsetX -85.0 mm 
/det/setScintDetectorOffsetY 0.0 mm 

/det/setNumScintPanelsPerLayer 2

/det/setScintWidth 42 cm
/det/setScintHeight 42 cm
/det/setScintBarWidth 10.0 mm
/det/setScintBarHeight 10.0 mm
/det/setScintThickness 5 mm

# Interface Pixel Tracker (IPT)
/det/setNumIPTLayers 3

/det/setAluminumWallThickness 2.0