# ======================================================
# Detector geometry setup  (/det/)
# ======================================================

# Pinpoint Geometry

# /det/setPinpointThickness 10.5 cm
/det/setNumPinpointLayers 4
/det/setPinpointTungstenThickness 8 mm

/det/setPixelDetectorOffsetX 0.0 mm
/det/setPixelDetectorOffsetY 0.0 mm

/det/setSiliconThickness 10 um
/det/setBoxThickness 4.990 mm

# Pixel dimensions
/det/setPixelHeight 22.8 um
/det/setPixelWidth 20.8 um

# Overall detector transverse size
/det/setDetectorWidth 26.6 cm
/det/setDetectorHeight 19.6 cm

# Fortune Geometry
/det/setNumFortuneBlocks 6

/det/setNumScintLayers 10

/det/setScintDetectorOffsetX -77.0 mm 
/det/setScintDetectorOffsetY 0.0 mm 

# Fortune tungsten thickness
/det/setTungstenThickness 5.0 mm

# Scintillator configuration
/det/setScintBarFlag true
#  true  = bar geometry
#  false = solid block

/det/setNumScintPanelsPerLayer 2
# /det/setScintWidth 27 cm
# /det/setScintHeight 60 cm
/det/setScintWidth 45 cm
/det/setScintHeight 45 cm
/det/setScintBarWidth 10.0 mm
/det/setScintBarHeight 10.0 mm
/det/setScintThickness 5 mm

# Interface Pixel Tracker (IPT)
/det/setNumIPTLayers 2 # 

/det/setAluminumWallThickness 2.0