# ======================================================
# Global control
# ======================================================
/control/verbose 1
/run/verbose 1

# ======================================================
# Detector geometry setup  (/det/)
# ======================================================
/control/execute macros/geom.mac

# ======================================================
# Global control
# ======================================================
/control/verbose 1
/run/verbose 1

# ======================================================
# Generator setup  (/gen/hepmc)
# ======================================================


/gen/select gun
/gps/particle mu-
/gps/pos/type Volume
/gps/pos/shape Para
/gps/ang/rot1 -1 0 0
/gps/pos/centre 0 0 -200 cm
/gps/pos/halfx 0.5 cm
/gps/pos/halfy 0.5 cm
/gps/pos/halfz 0.5 cm
/gps/ang/type iso
/gps/ang/maxtheta 0 deg
/gps/ang/mintheta 0 deg
/gps/ang/maxphi 360 deg
/gps/ang/minphi 0 deg

/gps/ene/type Gauss
/gps/ene/mono 300 GeV
/gps/ene/sigma 5 GeV

# ======================================================
# Output and analysis options  (/out/)
# ======================================================

# Output ROOT file name for histograms / ntuples
/out/fileName muons.root

# Flags for extra output detail
/tracking/storeTrajectory 1
/out/saveTrack true
/out/saveTruthHits true


# ======================================================
# Initialize and run
# ======================================================

/run/initialize
# (optionally geometry, cuts, etc., here if you have other messengers)

/run/beamOn 1000   # <-- set number of events

